##
## Credits to rxyhn's

format = "$all"
right_format = """$git_branch$git_status$cmd_duration$directory"""

# Disable the blank line at the start of the prompt
add_newline = true
continuation_prompt = "â–¶â–¶"

[line_break]
disabled = true

[character]
success_symbol = " [îŠ…](#395385)"
error_symbol = " [ï€](#df5b61)"
vicmd_symbol = "[ î˜« ](#78b892)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "[î‚¶](fg:#1c252c bg:none)[$duration]($style)[î‚´](fg:#1c252c bg:#1c252c)[î‚¶](fg:#bc83e3 bg:#1c252c)[ï‰’](fg:#1c252c bg:#bc83e3)[î‚´](fg:#bc83e3 bg:none) "
disabled = false
style = "fg:#d9d7d6 bg:#1c252c"

[directory]
format = "[î‚¶](fg:#1c252c bg:none)[$path]($style)[î‚´](fg:#1c252c bg:#1c252c)[î‚¶](fg:#6791c9 bg:#1c252c)[ï»](fg:#1c252c bg:#6791c9)[î‚´](fg:#6791c9 bg:none)"
style = "fg:#d9d7d6 bg:#1c252c"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[î‚¶](fg:#1c252c bg:none)[$branch]($style)[î‚´](fg:#1c252c bg:#1c252c)[î‚¶](fg:#78b892 bg:#1c252c)[ï˜](fg:#282c34 bg:#78b892)[î‚´](fg:#78b892 bg:none) "
style = "fg:#d9d7d6 bg:#1c252c"

[git_status]
format="[î‚¶](fg:#1c252c bg:none)[$all_status$ahead_behind]($style)[î‚´](fg:#1c252c bg:#1c252c)[î‚¶](fg:#67afc1 bg:#1c252c)[îœˆ](fg:#1c252c bg:#67afc1)[î‚´](fg:#67afc1 bg:none) "
style = "fg:#d9d7d6 bg:#1c252c"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"
